pipeline {
    agent any

    environment {
        VENV = "venv"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    credentialsId: 'github_credentials',
                    url: 'https://github.com/Eric-hack/alx-backend-python.git'
            }
        }

        stage('Install System Dependencies') {
            steps {
                script {
                    sh '''
                        apt-get update
                        apt-get install -y pkg-config libmysqlclient-dev build-essential python3-dev
                    '''
                }
            }
        }

        stage('Install Python Dependencies') {
            steps {
                script {
                    sh '''
                        python3 -m venv ${VENV}
                        . ${VENV}/bin/activate
                        pip install --upgrade pip
                        pip install -r messaging_app/requirements.txt
                    '''
                }
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    sh '''
                        . ${VENV}/bin/activate
                        pytest messaging_app/tests/ --junitxml=report.xml --maxfail=1 --disable-warnings
                    '''
                }
            }
            post {
                always {
                    junit 'report.xml'
                }
            }
        }
    }

    post {
        success {
            echo "✅ Tests passed successfully!"
        }
        failure {
            echo "❌ Tests failed! Please check the report."
        }
    }
}
